version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/gitchat/main.go  # Updated path
    ldflags:
      - -s -w
      - -X github.com/go-coders/gitchat/internal/version.Version={{.Version}}
      - -X github.com/go-coders/gitchat/internal/version.BuildTime={{.Date}}
      - -X github.com/go-coders/gitchat/internal/version.GitCommit={{.FullCommit}}
    binary: gitchat

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch

