// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// InputReader is an autogenerated mock type for the InputReader type
type InputReader struct {
	mock.Mock
}

type InputReader_Expecter struct {
	mock *mock.Mock
}

func (_m *InputReader) EXPECT() *InputReader_Expecter {
	return &InputReader_Expecter{mock: &_m.Mock}
}

// ReadString provides a mock function with given fields: delim
func (_m *InputReader) ReadString(delim byte) (string, error) {
	ret := _m.Called(delim)

	if len(ret) == 0 {
		panic("no return value specified for ReadString")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(byte) (string, error)); ok {
		return rf(delim)
	}
	if rf, ok := ret.Get(0).(func(byte) string); ok {
		r0 = rf(delim)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(byte) error); ok {
		r1 = rf(delim)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InputReader_ReadString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadString'
type InputReader_ReadString_Call struct {
	*mock.Call
}

// ReadString is a helper method to define mock.On call
//   - delim byte
func (_e *InputReader_Expecter) ReadString(delim interface{}) *InputReader_ReadString_Call {
	return &InputReader_ReadString_Call{Call: _e.mock.On("ReadString", delim)}
}

func (_c *InputReader_ReadString_Call) Run(run func(delim byte)) *InputReader_ReadString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(byte))
	})
	return _c
}

func (_c *InputReader_ReadString_Call) Return(_a0 string, _a1 error) *InputReader_ReadString_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InputReader_ReadString_Call) RunAndReturn(run func(byte) (string, error)) *InputReader_ReadString_Call {
	_c.Call.Return(run)
	return _c
}

// NewInputReader creates a new instance of InputReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInputReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *InputReader {
	mock := &InputReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
